trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    pytest
  displayName: 'Install dependencies and run tests'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)
    cp report.xml $(Build.ArtifactStagingDirectory)
  displayName: 'Copy test report to artifact staging directory'
  condition: 

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'test-results'
    publishLocation: 'Container'
